---
title: "¿Cómo calcular la incertidumbre de una curva de calibración?"
description: |
  A short description of the post.
author:
  - name: Nora Jones
    url: https://example.com/norajones
date: 2021-11-05
output:
  distill::distill_article:
    self_contained: false
---

Ok, este es el segundo post pero advierto que aún está en rodaje... esto del
_copywriting_ no es nada fácil.

>¿Qué es y cómo estimar la incertidumbre de una curva de calibración?

La incertidumbre de calibración, en adelante $u(x_{0})$, es aquella que se 
propaga cuando obtenemos la concentración de un mensurando
al *interpolar* una señal instrumental (por ejemplo, absorbancia o 
área cromatográfica) en una curva de calibración. Básicamente, 
esta incertidumbre
sólo da cuenta del error aleatorio del instrumento y no incopora la
incertidumbre de los calibrantes, al menos cuando se utiliza el modelo de 
calibración clásico:

\begin{equation}
  y = \beta_{0} + \beta_{1} x + \epsilon
    (\#eq:lin)
\end{equation}

donde $y$ es la respuesta instrumental, $\beta_{0}$ es el intercepto,
$\beta_{1}$ es la pendiente y $\epsilon$ es un error aleatorio Normal que tiene
media $\mu_{\epsilon} = 0$ y varianza $\sigma_{y/x}^2$. Note de la 
ecuación \@ref(eq:lin) que lo único aleatorio es $\epsilon$, por lo tanto,
el intercepto $\beta_{0}$  y la pendiente $\beta_{1}$ son *fijos*. 
Lo que hacemos cuando aplicamos, por ejemplo, el método de los mínimos 
cuadrados es estimar estos parámetros y, en estadística, todas las 
estimaciones tienen un error asociado.

A partir de la ecuación \@ref(eq:lin) obtenemos la concentración de una 
muestra problema $x_{0}$ cuya señal instrumental es $y_{0}$:

\begin{equation}
  x_{0} = \frac{y_{0} - \beta_{0}}{\beta_{1}}
    (\#eq:x0)
\end{equation}

Si aplicáramos la guía GUM para obtener la incertidumbre estándar de 
calibración $u(x_{0})$ sería bastante latoso-engorroso, pues hay unas 
covarianzas no muy amistosas entre pendiente e intercepto. Afortunadamente
$u(x_{0})$ puede aproximarse muy bien a través de la ecuación \@ref(eq:ux0):

\begin{equation}
  u(x_{0}) = \frac{\sigma_{y/x}}{\beta_{1}}
  \sqrt{\frac{1}{n} + \frac{1}{m_{0}} + \frac{(x_{0} - \overline{x})^2}
  {\sum_{i}^{n} (x_{i} - \overline{x})^2}}
    (\#eq:ux0)
\end{equation}

Vamos viendo dijo el ciego:

- $\sigma_{y/x}$ es la desviación estándar del error aleatorio $\epsilon$
- $n$ es el número de calibrantes independientes (esto da para otro post)
- $m_{0}$ es el número de replicado independientes de la muestra problema
- $\overline{x}$ es el promedio de la concentraciones de los calibrantes


Esta incertidumbre se puede observar en la figura \@ref(fig:banda), la
cual fue obtenida mediante simulación en lenguaje `R`:
  
```{r banda, fig.cap = 'Incertidumbre de calibracion'}

set.seed(123)
x <- 1:10
y <- 2 + 5*x + 10*rnorm(length(x), 0, 1)
d <- data.frame(x, y)

library(ggplot2)

ggplot(d, aes(x = x, y = y)) +
  geom_smooth(method = 'lm') 

```

